# Generated by Django 4.2.7 on 2023-11-10 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('parent_id', models.IntegerField()),
                ('is_enabled', models.BooleanField()),
                ('description', models.TextField()),
                ('owner', models.IntegerField()),
                ('belong_to', models.JSONField()),
                ('has_many', models.JSONField()),
                ('attribute', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_data', models.JSONField()),
                ('user_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('entity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.entity')),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_entity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_entity', to='form.entity')),
                ('fk_value_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_value', to='form.value')),
                ('pk_entity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pk_entity', to='form.entity')),
                ('pk_value_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pk_value', to='form.value')),
            ],
        ),
    ]
