# Generated by Django 4.2.7 on 2023-11-13 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='attribute',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='belong_to',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='description',
            field=models.CharField(max_length=555, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='has_many',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='is_enabled',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='owner',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='parent_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='value',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='value',
            name='entity_data',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='value',
            name='entity_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='form.entity'),
        ),
        migrations.AlterField(
            model_name='value',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='value',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
