# Generated by Django 4.2.7 on 2023-11-15 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_alter_entity_attribute_alter_entity_belong_to_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relation',
            old_name='fk_entity_id',
            new_name='fk_entity',
        ),
        migrations.RenameField(
            model_name='relation',
            old_name='fk_value_id',
            new_name='fk_value',
        ),
        migrations.RenameField(
            model_name='relation',
            old_name='pk_entity_id',
            new_name='pk_entity',
        ),
        migrations.RenameField(
            model_name='relation',
            old_name='pk_value_id',
            new_name='pk_value',
        ),
        migrations.RenameField(
            model_name='value',
            old_name='entity_id',
            new_name='entity',
        ),
    ]
