# Generated by Django 4.2.7 on 2023-11-16 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_rename_fk_entity_id_relation_fk_entity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='is_menu',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='route',
            field=models.JSONField(null=True),
        ),
    ]
